language: python

python:
  - "3.5"

sudo: false
cache: pip

addons:
  postgresql: "9.2" # minimal postgresql version for the daterange method
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - unixodbc-dev

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: ABaQffZycmzdJs9Slg4OLC8K+wnmpkS5R7bEIOAgsZYMYnOntZz6SzhF8/TOqI2hdUyvxgyVLhUlZdLrgogUgG/V2QjdmIErE6+x4iHECgQ4iXvhqtTpN2S/SVyjVP+7QE8Ugnth/tykWxXpgMpkuA6xnGC2HU8r/s4261tys4g=

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install unicodecsv
  - pip install codicefiscale
  - pip install unidecode==0.04.17
  - pip install PyXB==1.2.4

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
